project:
  type: website
  output-dir: docs

website:
  navbar:
    logo: "logo_amrc.png" 
    right:
      - href: index.qmd
        text: Home
      - about.qmd
    background: "#ffffff"
    foreground: "#333333"
  announcement: 
    dismissable: false
    content: "Applied Measuresment & Research Center"
    type: primary
    position: below-navbar

format:
  html:
    theme: lux
    css: styles.css
    toc: true




