project:
  type: website
  output-dir: docs

website:
  title: "Applied Measurement & Research Center"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    background: "#ffffff"
    foreground: "#333333"

format:
  html:
    theme: lux
    css: styles.css
    toc: true



